spring:
  h2:
    console:
      enable: true
      path: /h2
  datasource:
    url: jdbc:h2:~/dbempresa
    data:
      username: sa
      password: everis
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true